### ISSUE TITLE
Links dos artigos do Medium no teu README

### ISSUE THREAD

**Issue by jrhumberto** [lucas-sls/Prevendo_churn_clientes#1]
Como sugestão, teu projeto ficou ótimo, para facilitar a organização e evitar excesso de arquivos ,coloca tua listagem de links em formato Markdown no próprio README, podendo apagar o arquivo [txt](https://github.com/lucas-sls/Prevendo_churn_clientes/blob/main/LINKS%20PARA%20ARTIGOS%20NO%20MEDIUM.txt)

**Comment by lucas-sls** [comment]
Oi Humberto, tudo bem? Ótima sugestão! Muito obrigado pela dica! Já arrumei no projeto. Quando puder vai lá dar uma olhada. Espero que curta!
